Cypress.Commands.add('fillMandatoryFieldsAndSubmit', () => {
    cy.get('#firstName').type('Viviane')
    cy.get('#lastName').type('Correa')
    cy.get('#email').type('vivianecorreasv@gmail.com')
    cy.get('#phone').type('51 9953764')
    cy.get('#product').select('mentoria')
    cy.get('#support-type').find('input[name="atendimento-tat"][value="feedback"]').check()                              
    cy.get('#check').find('input[name=email][value=email]').check()
    cy.get('#open-text-area').type(longText, {delay: 0})
    cy.get('button[type="submit"]').click()
})